#!/bin/sh

set -e

if [ -z "$POSTGRES_PIM_USER" ] || [ -z "$POSTGRES_PIM_PASSWORD" ]; then
  echo "Error: Both POSTGRES_PIM_USER and POSTGRES_PIM_PASSWORD must be defined in container configuration."
  exit 1
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOF
CREATE USER $POSTGRES_PIM_USER WITH PASSWORD '$POSTGRES_PIM_PASSWORD';
CREATE DATABASE $POSTGRES_PIM_DB;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_PIM_DB TO $POSTGRES_PIM_USER;
EOF

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_PIM_DB" <<EOF
GRANT ALL ON SCHEMA public TO $POSTGRES_PIM_USER;
EOF

if [ -z "$POSTGRES_PIM_DB_TEST" ]; then
  exit 0
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOF
CREATE DATABASE $POSTGRES_PIM_DB_TEST;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_PIM_DB_TEST TO $POSTGRES_PIM_USER;
EOF

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_PIM_DB_TEST" <<EOF
GRANT ALL ON SCHEMA public TO $POSTGRES_PIM_USER;
EOF
